<?php
// BANK SOAL UTAMA - 2 SESI @ 10 SOAL
$quiz_data = [
    'sesi_1' => [
        'title' => 'Kuis Sesi 1: Fondasi Keamanan',
        'questions' => [
            ['question' => "Anda menerima email dari 'noreply@bnk-bca.com' yang meminta verifikasi data. Apa tanda bahaya utama di sini?", 'options' => ["Nama pengirim 'noreply'", "Meminta verifikasi data", "Alamat email 'bnk-bca.com' yang salah eja", "Email dikirim di luar jam kerja"], 'answer' => 2, 'explanation' => "Alamat email resmi tidak akan menggunakan ejaan yang salah. 'bnk-bca.com' adalah contoh klasik domain palsu yang mencoba meniru 'bca.co.id' atau domain resmi lainnya."],
            ['question' => "Manakah metode Autentikasi Dua Faktor (2FA) yang paling rentan terhadap serangan SIM Swap?", 'options' => ["Aplikasi Authenticator (Google/Authy)", "Kunci Keamanan Fisik (YubiKey)", "Kode verifikasi yang dikirim via SMS", "Sidik jari (biometrik)"], 'answer' => 2, 'explanation' => "2FA via SMS paling rentan karena jika penipu berhasil mengambil alih nomor HP Anda melalui SIM Swap, semua kode OTP akan masuk ke perangkat mereka."],
            ['question' => "Anda mengunduh sebuah software 'gratis' dari situs tidak resmi. Setelah diinstal, laptop menjadi sangat lambat dan penuh iklan. Jenis malware apa yang paling mungkin menginfeksi?", 'options' => ["Worm", "Trojan yang membawa Adware/Spyware", "Ransomware", "Virus Boot Sector"], 'answer' => 1, 'explanation' => "Trojan adalah malware yang menyamar sebagai program sah (seperti software gratis). Seringkali, 'bonus' yang ia bawa adalah Adware (untuk iklan) dan Spyware (untuk memata-matai)."],
            ['question' => "Prinsip 'Panjang Lebih Baik dari Rumit' paling relevan saat membuat...", 'options' => ["PIN ATM", "Password Akun Online", "Kode OTP", "Username"], 'answer' => 1, 'explanation' => "Untuk password, sebuah 'passphrase' yang panjang (misal: 'kuda-terbang-makan-donat-ungu') jauh lebih sulit dipecahkan oleh komputer daripada password pendek yang rumit seperti 'PsWd!@#$'."],
            ['question' => "Saat berada di Wi-Fi publik (misal: bandara), apa langkah pengamanan terbaik sebelum melakukan transaksi perbankan?", 'options' => ["Menggunakan mode Incognito di browser", "Memastikan situsnya menggunakan HTTPS", "Menggunakan koneksi VPN (Virtual Private Network)", "Mematikan Bluetooth"], 'answer' => 2, 'explanation' => "VPN akan mengenkripsi semua lalu lintas data Anda, menciptakan 'terowongan' aman di dalam jaringan publik yang tidak aman. HTTPS penting, tapi VPN memberikan lapisan perlindungan yang jauh lebih komprehensif."],
            ['question' => "Seorang teman di media sosial tiba-tiba mengirim pesan berisi link aneh dengan tulisan 'Hei, lihat video memalukanmu di sini!'. Ini adalah contoh dari...", 'options' => ["Serangan Ransomware", "Rekayasa Sosial (Social Engineering)", "Serangan Brute Force", "Malware Trojan"], 'answer' => 1, 'explanation' => "Rekayasa Sosial adalah seni memanipulasi psikologi seseorang (rasa penasaran, panik, takut) untuk membuat mereka melakukan tindakan yang tidak aman, seperti mengklik link berbahaya."],
            ['question' => "Apa fungsi utama dari melakukan backup data dengan strategi 3-2-1?", 'options' => ["Membuat komputer lebih cepat", "Memastikan selalu ada salinan data yang selamat jika terjadi bencana atau serangan ransomware", "Menghemat ruang penyimpanan di hard disk utama", "Agar bisa berbagi file dengan mudah"], 'answer' => 1, 'explanation' => "Tujuan utama backup adalah pemulihan data. Jika perangkat utama rusak atau data dikunci oleh ransomware, Anda masih memiliki salinan aman di tempat lain."],
            ['question' => "Anda menemukan USB flash drive di toilet kantor. Tindakan paling bijak adalah...", 'options' => ["Mencolokkannya ke komputer pribadi untuk melihat isinya", "Mencolokkannya ke komputer kantor yang sudah ada antivirus", "Menyerahkannya ke bagian keamanan atau IT tanpa mencolokkannya sama sekali", "Memformatnya agar bisa digunakan sendiri"], 'answer' => 2, 'explanation' => "USB drive yang tidak dikenal bisa saja berisi malware yang akan otomatis berjalan (autorun) saat dicolokkan. Ini adalah metode serangan klasik yang disebut 'USB Drop Attack'."],
            ['question' => "Password Manager membantu meningkatkan keamanan dengan cara...", 'options' => ["Membuat semua password menjadi sama agar mudah diingat", "Menyimpan password dalam file teks di desktop", "Memungkinkan penggunaan password yang sangat kuat dan unik untuk setiap akun", "Menyembunyikan ikon aplikasi di HP"], 'answer' => 2, 'explanation' => "Kekuatan utama Password Manager adalah kemampuannya untuk membuat dan mengingat puluhan password yang panjang, acak, dan unik untuk setiap situs, sesuatu yang hampir tidak mungkin dilakukan oleh manusia."],
            ['question' => "Anda melihat gembok HTTPS di address bar browser. Apa artinya?", 'options' => ["Situs web ini 100% aman dari semua jenis serangan", "Situs web ini dimiliki oleh pemerintah", "Koneksi antara browser Anda dan server situs web ini terenkripsi", "Situs web ini tidak memiliki iklan"], 'answer' => 2, 'explanation' => "HTTPS (Hypertext Transfer Protocol Secure) memastikan bahwa data yang Anda kirim dan terima dari situs tersebut dienkripsi, sehingga tidak bisa 'diintip' oleh pihak ketiga di tengah jalan. Ini tidak menjamin situsnya sendiri bebas dari malware atau phishing."],
        ]
    ],
    'sesi_2' => [
        'title' => 'Kuis Sesi 2: Skenario & Ancaman Lanjutan',
        'questions' => [
            // 10 Soal Sesi 2 (Baru)
            ['question' => "Saat melakukan 'factory reset' pada HP Android sebelum menjualnya, apa yang sebenarnya terjadi pada data lama Anda?", 'options' => ["Data terhapus permanen dan tidak bisa dipulihkan", "Data hanya disembunyikan dan masih bisa dipulihkan dengan software khusus", "Data dienkripsi sehingga tidak bisa dibaca", "Data otomatis di-backup ke cloud"], 'answer' => 1, 'explanation' => "Factory reset standar hanya menghapus 'indeks' data. Data fisiknya masih ada dan bisa dipulihkan. Untuk keamanan, enkripsi perangkat Anda SEBELUM melakukan factory reset."],
            ['question' => "Seorang 'teman' online yang baru Anda kenal selama seminggu tiba-tiba meminta bantuan pinjaman uang untuk 'ibunya yang sakit'. Ini adalah ciri utama dari...", 'options' => ["Serangan Man-in-the-Middle", "Serangan Ransomware", "Penipuan Romantis (Romance Scam)", "Serangan Zero-Day"], 'answer' => 2, 'explanation' => "Penipuan Romantis (Romance Scam) adalah teknik rekayasa sosial di mana pelaku membangun hubungan emosional palsu untuk kemudian mengeksploitasi korban secara finansial."],
            ['question' => "Situs web mana yang paling aman untuk menyimpan dan mengelola password Anda?", 'options' => ["Google Docs atau catatan di HP", "File Excel yang diberi password", "Tidak ada di antara pilihan ini", "Mengirimkannya ke email sendiri"], 'answer' => 2, 'explanation' => "Tidak ada dari pilihan tersebut yang aman. Solusi paling aman adalah menggunakan aplikasi Password Manager yang dirancang khusus dengan enkripsi yang kuat."],
            ['question' => "Anda mendapat telepon dari nomor tak dikenal yang mengaku dari pihak bank dan meminta Anda menyebutkan kode OTP yang baru saja masuk ke SMS. Apa yang harus Anda lakukan?", 'options' => ["Menyebutkan kodenya karena dia dari pihak bank", "Menutup telepon dan segera memblokir nomornya", "Meminta dia menelepon kembali nanti", "Menanyakan nama lengkap dan NIK petugas"], 'answer' => 1, 'explanation' => "Jangan pernah memberikan kode OTP kepada siapa pun. OTP adalah kunci rahasia Anda. Pihak bank atau institusi resmi tidak akan pernah memintanya. Ini adalah modus Vishing (Voice Phishing)."],
            ['question' => "Apa itu 'Zero-Day Exploit'?", 'options' => ["Serangan yang terjadi pada hari pertama setiap bulan", "Celah keamanan yang belum diketahui oleh pembuat software dan belum ada perbaikannya", "Virus yang menghapus semua data dalam waktu nol detik", "Serangan yang hanya berhasil pada sistem operasi Windows 0"], 'answer' => 1, 'explanation' => "Disebut 'Zero-Day' karena developer memiliki 'nol hari' untuk memperbaikinya saat pertama kali ditemukan oleh peretas. Ini adalah salah satu ancaman paling berbahaya."],
            ['question' => "Di sebuah kafe, ada dua jaringan Wi-Fi: 'Starbucks_Free' dan 'Starbucks_Free_WiFi'. Keduanya tanpa password. Ini kemungkinan adalah contoh dari serangan...", 'options' => ["DDoS", "Evil Twin", "SQL Injection", "Botnet"], 'answer' => 1, 'explanation' => "Serangan Evil Twin adalah saat peretas membuat hotspot Wi-Fi palsu dengan nama yang sangat mirip dengan yang asli untuk menjebak pengguna dan mencuri data mereka."],
            ['question' => "Mengapa menggunakan antivirus bajakan atau 'crack' sangat tidak disarankan?", 'options' => ["Karena fiturnya tidak selengkap versi asli", "Karena seringkali sudah disisipi malware oleh pembuat crack-nya", "Karena warnanya tidak bagus", "Karena membuat komputer jadi lambat"], 'answer' => 1, 'explanation' => "Sangat ironis, tetapi software keamanan bajakan seringkali menjadi sumber infeksi malware. Anda mencoba melindungi diri, tapi malah membuka pintu untuk ancaman yang lebih besar."],
            ['question' => "Anda melihat sebuah postingan di media sosial yang mengklaim 'NASA menemukan bukti kehidupan di Mars!' dengan link ke sebuah situs berita yang belum pernah Anda dengar. Langkah paling bijak adalah...", 'options' => ["Langsung membagikan postingan tersebut agar semua teman tahu", "Mengklik link untuk membaca beritanya", "Melakukan pengecekan silang (cross-check) ke beberapa situs berita besar dan terpercaya terlebih dahulu", "Mengomentari 'Wow, keren!'"], 'answer' => 2, 'explanation' => "Ini adalah langkah dasar literasi digital. Sebelum mempercayai atau menyebarkan informasi yang sensasional, selalu verifikasi kebenarannya dari beberapa sumber yang memiliki reputasi baik untuk menghindari hoaks atau situs berbahaya."],
            ['question' => "Apa tujuan utama dari serangan DDoS (Distributed Denial-of-Service)?", 'options' => ["Mencuri password admin", "Membuat sebuah situs web atau layanan menjadi tidak bisa diakses (lumpuh)", "Mengenkripsi file di server", "Memasang iklan di situs web target"], 'answer' => 1, 'explanation' => "Tujuan DDoS adalah membanjiri server target dengan lalu lintas internet palsu dari ribuan komputer (botnet) hingga server tersebut kewalahan dan tidak bisa melayani pengguna asli."],
            ['question' => "Kebijakan privasi sebuah aplikasi menyatakan, 'Kami dapat membagikan data Anda dengan mitra pihak ketiga untuk tujuan pemasaran'. Apa artinya ini bagi Anda?", 'options' => ["Data Anda aman karena hanya dibagikan ke mitra", "Aplikasi ini sangat menjaga privasi", "Informasi pribadi Anda kemungkinan akan digunakan untuk iklan tertarget atau bahkan dijual", "Anda akan mendapatkan diskon dari mitra mereka"], 'answer' => 2, 'explanation' => "Kalimat seperti ini adalah cara halus untuk mengatakan bahwa data Anda (seperti kebiasaan Browse, minat, lokasi) akan dibagikan atau dijual ke perusahaan lain untuk keperluan iklan."],
        ]
    ]
];
?>