<?php
// INI ADALAH BANK DATA FINAL DENGAN SYNTAX YANG SUDAH DIPERBAIKI
$learning_data = [
    'malware' => [
        'title' => 'Ancaman Malware',
        'subtitle' => 'Dasar-Dasar, Jenis, dan Pencegahan',
        'icon' => 'fa-shield-virus',
        'chapters' => [
            1 => [
                'title' => 'Pengenalan & Jenis-Jenis Dasar',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Apa itu Malware?', 'duration' => '4 menit', 'content' => "<h3>Definisi Mendalam Malware</h3><p>Malware, singkatan dari <strong>'malicious software'</strong> (perangkat lunak jahat), adalah istilah umum untuk semua jenis program yang dirancang dengan tujuan merugikan. Tujuan utamanya bisa beragam:</p><ul><li><strong>Mencuri Data:</strong> Mengambil informasi sensitif seperti password, nomor kartu kredit, atau data pribadi untuk dijual atau disalahgunakan.</li><li><strong>Merusak Sistem:</strong> Menghapus file, merusak sistem operasi, atau membuat perangkat Anda tidak bisa digunakan sama sekali.</li><li><strong>Mengganggu Pengguna:</strong> Menampilkan iklan yang tidak diinginkan secara terus-menerus (Adware).</li><li><strong>Menyediakan Akses Ilegal:</strong> Memberi peretas 'pintu belakang' untuk mengontrol perangkat Anda dari jarak jauh dan menjadikannya bagian dari 'pasukan zombie' (Botnet).</li></ul><p>Anggap saja malware sebagai istilah umum untuk semua 'penjahat digital' yang bisa masuk ke perangkat Anda.</p>"],
                    2 => ['type' => 'kuis', 'title' => 'Kuis: Definisi', 'duration' => '1 menit', 'question' => "Istilah 'Malware' merupakan singkatan dari...", 'options' => ["Mail-Software", "Malicious Software", "Main-Software"], 'answer' => 1 ],
                    3 => ['type' => 'materi', 'title' => 'Mengenal Virus dan Worm', 'duration' => '5 menit', 'content' => "<h3>Virus vs. Worm: Siapa Butuh Tumpangan?</h3><p>Meskipun sering dianggap sama, keduanya punya cara menyebar yang fundamentalnya berbeda:</p><blockquote><strong>Virus</strong> seperti penumpang gelap. Ia tidak bisa berjalan sendiri. Ia harus 'menempel' pada file atau program lain yang sah (disebut 'inang'), seperti file <code>.exe</code> atau dokumen Word. Saat Anda membuka file inang tersebut, virus baru akan aktif dan mulai menginfeksi file-file lain.</blockquote><blockquote><strong>Worm (Cacing)</strong> lebih mandiri dan berbahaya dalam penyebarannya. Ia seperti perampok yang punya mobil sendiri. Worm adalah program mandiri yang bisa mereplikasi (menggandakan) dirinya sendiri dan menyebar ke komputer lain melalui jaringan (internet/LAN) tanpa perlu campur tangan manusia atau menempel pada program lain.</blockquote>"],
                    4 => ['type' => 'kuis', 'title' => 'Kuis: Virus vs Worm', 'duration' => '2 menit', 'question' => "Jenis malware yang bisa menyebar sendiri melalui jaringan tanpa perlu program inang disebut...", 'options' => ["Virus", "Trojan", "Worm"], 'answer' => 2 ],
                ]
            ],
            2 => [
                'title' => 'Ancaman Populer Saat Ini',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Trojan: Penipu dalam Selimut', 'duration' => '5 menit', 'content' => "<h3>Legenda Kuda Troya di Dunia Digital</h3><p>Sesuai namanya, <strong>Trojan</strong> adalah master penyamaran. Ia masuk ke sistem Anda dengan menyamar sebagai sesuatu yang sah dan berguna (misalnya, game gratis, aplikasi edit foto), namun di dalamnya tersembunyi program jahat. Saat Anda menjalankannya, Anda tanpa sadar telah membuka 'pintu gerbang' bagi program jahat yang tersembunyi di dalamnya.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Ransomware: Sang Penyandera Digital', 'duration' => '6 menit', 'content' => "<h3>'Data Anda Terkunci, Bayar atau Hilang Selamanya!'</h3><p><strong>Ransomware</strong> adalah salah satu jenis malware paling merusak dan meresahkan. Cara kerjanya sangat kejam:</p><ol><li><strong>Infeksi:</strong> Masuk ke perangkat Anda, biasanya melalui email phishing atau software bajakan.</li><li><strong>Enkripsi:</strong> Secara diam-diam, ia akan mengenkripsi (mengunci dengan kode rahasia super rumit) semua file penting Anda—dokumen kerja, foto keluarga, video, database, dll.</li><li><strong>Pesan Tebusan:</strong> Sebuah pesan akan muncul di layar, memberitahu bahwa file Anda telah disandera dan Anda harus membayar sejumlah uang (biasanya dalam bentuk cryptocurrency seperti Bitcoin) untuk mendapatkan kunci pembukanya.</li></ol><p><strong>PENTING:</strong> Badan keamanan siber di seluruh dunia menyarankan untuk <strong>TIDAK MEMBAYAR TEBUSAN</strong>. Tidak ada jaminan file Anda akan kembali, dan itu hanya akan mendanai kegiatan kriminal mereka.</p>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Ransomware', 'duration' => '2 menit', 'question' => "Malware yang mengunci file dan meminta tebusan disebut...", 'options' => ["Spyware", "Ransomware", "Adware"], 'answer' => 1 ],
                ]
            ],
            3 => [
                'title' => 'Pencegahan & Penanganan Darurat',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => '5 Pilar Pencegahan Malware', 'duration' => '7 menit', 'content' => "<h3>Membangun Benteng Pertahanan</h3><p>Mencegah selalu lebih baik daripada mengobati. Berikut adalah 5 pilar utama untuk melindungi diri dari malware:</p><ol><li><strong>Gunakan Antivirus & Firewall:</strong> Anggap Antivirus sebagai satpam yang patroli di dalam rumah, dan Firewall sebagai tembok dan gerbang yang menyaring siapa yang boleh masuk. Gunakan keduanya dan pastikan selalu update.</li><li><strong>Waspada Saat Online:</strong> Jangan mengunduh file dari sumber yang tidak resmi atau situs bajakan. Ini adalah jalur utama penyebaran malware.</li><li><strong>Jangan Asal Klik:</strong> Waspada terhadap lampiran email atau link dari pengirim yang tidak dikenal. Verifikasi dulu sebelum mengklik apapun.</li><li><strong>Selalu Lakukan Update:</strong> 'Tambalan keamanan' (security patches) yang ada di setiap update sistem operasi (Windows, MacOS, Android) dan aplikasi (Chrome, Office) sangat krusial untuk menutup celah yang bisa dieksploitasi malware.</li><li><strong>Strategi Backup 3-2-1:</strong> Ini adalah jaring pengaman terakhir Anda melawan ransomware. Simpan <strong>3</strong> salinan data penting Anda, di <strong>2</strong> jenis media yang berbeda (misal: di laptop dan di hard disk eksternal), dengan <strong>1</strong> salinan berada di lokasi yang berbeda (off-site, seperti di cloud atau di rumah teman).</li></ol>"],
                    2 => ['type' => 'kuis', 'title' => 'Kuis: Pencegahan', 'duration' => '2 menit', 'question' => "Tindakan paling efektif untuk melindungi data dari kehilangan akibat serangan ransomware adalah...", 'options' => ["Memasang wallpaper baru", "Melakukan backup data rutin", "Membersihkan keyboard"], 'answer' => 1 ],
                ]
            ],
            4 => [
                'title' => 'Mata-Mata & Pengiklan Paksa',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Spyware: Si Pengintai Aktivitas', 'duration' => '6 menit', 'content' => "<h3>Setiap Gerakanmu Diawasi</h3><p><strong>Spyware</strong> adalah jenis malware yang dirancang untuk 'memata-matai' Anda secara diam-diam. Setelah terpasang, ia bisa:</p><ul><li><strong>Merekam Ketikan (Keylogging):</strong> Mencatat semua yang Anda ketik, termasuk password, pesan pribadi, dan informasi kartu kredit.</li><li><strong>Mengambil Screenshot:</strong> Mengambil gambar layar Anda secara berkala.</li><li><strong>Memantau Aktivitas Web:</strong> Melihat situs apa saja yang Anda kunjungi.</li></ul><p>Data yang dicuri ini kemudian dikirim ke peretas untuk disalahgunakan, misalnya untuk penipuan atau pencurian identitas.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Adware: Agresif & Mengganggu', 'duration' => '5 menit', 'content' => "<h3>Banjir Iklan yang Tak Diundang</h3><p><strong>Adware</strong> (Advertising-supported software) sebenarnya tidak selalu jahat, namun bisa menjadi sangat mengganggu dan membahayakan. Adware yang agresif akan:</p><ul><li>Menampilkan iklan pop-up yang tidak relevan secara terus-menerus.</li><li>Mengubah halaman utama (homepage) browser Anda.</li><li>Mengalihkan pencarian Anda ke situs web iklan.</li></ul><p>Bahayanya, banyak Adware yang juga menyisipkan Spyware di dalamnya (malvertising) atau mengarahkan Anda ke situs phishing.</p>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Spyware vs Adware', 'duration' => '2 menit', 'question' => "Malware yang fokus utamanya adalah mencuri informasi dengan merekam ketikan disebut...", 'options' => ["Adware", "Spyware", "Ransomware"], 'answer' => 1 ],
                ]
            ],
            5 => [
                'title' => 'Keamanan Proaktif & Masa Depan',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Prinsip \'Least Privilege\'', 'duration' => '5 menit', 'content' => "<h3>Beri Akses Seperlunya Saja</h3><p>Prinsip 'Least Privilege' (Hak Istimewa Terkecil) adalah konsep keamanan fundamental. Artinya, jalankan program atau akun pengguna dengan hak akses seminimal mungkin yang diperlukan untuk bekerja.</p><p>Misalnya, jangan selalu menggunakan akun Administrator untuk pekerjaan sehari-hari di Windows. Gunakan akun standar. Ini akan sangat membatasi kemampuan malware untuk menginfeksi file sistem jika ia berhasil masuk.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Analisis Perilaku (Behavioral Analysis)', 'duration' => '6 menit', 'content' => "<h3>Mengenali Gerak-Gerik Mencurigakan</h3><p>Antivirus modern tidak hanya bergantung pada database virus yang sudah dikenal. Mereka juga menggunakan <strong>Analisis Perilaku</strong>. Mereka akan mengawasi program yang berjalan dan mencari tindakan mencurigakan, seperti:</p><ul><li>Sebuah program tiba-tiba mencoba mengenkripsi banyak file (ciri Ransomware).</li><li>Sebuah aplikasi tiba-tiba mencoba mengakses webcam tanpa izin (ciri Spyware).</li></ul><p>Jika terdeteksi, antivirus akan segera memblokir program tersebut meskipun virusnya belum teridentifikasi secara resmi.</p>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Keamanan Proaktif', 'duration' => '2 menit', 'question' => "Menggunakan akun non-Administrator untuk aktivitas harian di komputer adalah penerapan dari prinsip...", 'options' => ["Backup 3-2-1", "Least Privilege", "Zero Trust"], 'answer' => 1 ],
                ]
            ]
        ]
    ],
    'phishing' => [
        'title' => 'Jebakan Phishing',
        'subtitle' => 'Rekayasa Sosial & Penipuan',
        'icon' => 'fa-fish',
        'chapters' => [
            1 => [
                'title' => 'Dasar-Dasar & Psikologi Phishing',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Apa itu Phishing?', 'duration' => '4 menit', 'video_embed_url' => 'https://www.youtube.com/embed/o_m_03FjQyM', 'content' => "<h3>Seni Menipu Digital</h3><p>Phishing adalah serangan siber yang berfokus pada <strong>psikologi manusia</strong>, bukan pada peretasan teknis yang rumit. Pelaku (disebut phisher) mencoba 'memancing' Anda agar secara sukarela memberikan informasi sensitif.</p><p>Mereka melakukannya dengan cara menyamar sebagai pihak atau institusi tepercaya—misalnya bank, layanan e-commerce, bahkan teman atau atasan Anda—dan mengirimkan pesan palsu yang dirancang untuk terlihat asli.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Psikologi di Balik Jebakan', 'duration' => '5 menit', 'content' => "<h3>Memanfaatkan Emosi Manusia</h3><p>Serangan phishing seringkali berhasil karena memanipulasi emosi dasar kita untuk membuat kita tidak berpikir jernih. Taktik yang umum digunakan adalah:</p><ul><li><strong>Menciptakan Rasa Takut & Urgensi:</strong> Pesan seperti 'Akun Anda akan ditutup dalam 24 jam!' atau 'Ada transaksi mencurigakan, segera verifikasi!' membuat kita panik dan ingin segera bertindak.</li><li><strong>Memicu Keserakahan:</strong> Notifikasi 'Selamat, Anda memenangkan undian sebesar Rp 50 Juta! Klaim hadiah Anda di sini!' menargetkan keinginan kita untuk mendapatkan sesuatu dengan mudah.</li><li><strong>Memanfaatkan Kepercayaan & Keingintahuan:</strong> Pesan dari 'teman' yang mengirim link aneh, atau subjek email yang membuat penasaran, seringkali menjadi umpan yang efektif.</li></ul>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Psikologi Phishing', 'duration' => '2 menit', 'question' => "Email yang berisi 'Segera klik link ini atau akun bank Anda akan diblokir!' memanfaatkan emosi apa?", 'options' => ["Keserakahan", "Kepanikan", "Penasaran"], 'answer' => 1 ],
                ]
            ],
            2 => [
                'title' => 'Anatomi & Varian Serangan',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Anatomi Lengkap Email Phishing', 'duration' => '7 menit', 'video_embed_url' => 'https://www.youtube.com/embed/z1IIiP34g2E', 'content' => "<h3>Bongkar Kedok Penipu: Cek 5 Hal Ini!</h3><p>Jadilah seorang detektif setiap kali Anda menerima email yang mencurigakan. Periksa 5 hal ini secara teliti:</p><ol><li><strong>Alamat Pengirim (From):</strong> Jangan hanya lihat namanya, lihat alamat email lengkapnya. Apakah resmi? Email dari BCA tidak akan menggunakan domain <code>@gmail.com</code>. Perhatikan juga ejaan yang sengaja disalahkan, misal <code>admin@paypa1.com</code> (menggunakan angka 1 bukan L).</li><li><strong>Sapaan Generik:</strong> Waspada jika email penting menyapa Anda dengan 'Yth. Nasabah' atau 'Dear Customer', bukan nama lengkap Anda.</li><li><strong>Link yang Mencurigakan:</strong> Arahkan kursor mouse Anda ke atas link atau tombol (<strong>JANGAN DIKLIK!</strong>). Lihat alamat URL asli yang muncul di pojok kiri bawah browser. Jika alamatnya aneh (misal: <code>klik-disini-hadiah.xyz</code>), itu adalah link phishing.</li><li><strong>Tata Bahasa & Desain Buruk:</strong> Banyak pesan phishing yang memiliki tata bahasa aneh atau kualitas gambar yang rendah.</li><li><strong>Lampiran (Attachment) Berbahaya:</strong> Jangan pernah membuka lampiran yang tidak Anda harapkan, terutama file dengan ekstensi <code>.exe</code> atau <code>.zip</code>.</li></ol>"],
                    2 => ['type' => 'kuis', 'title' => 'Kuis: Deteksi Phishing', 'duration' => '2 menit', 'question' => "Cara terbaik untuk memeriksa keaslian sebuah link di email adalah dengan...", 'options' => ["Langsung mengkliknya untuk melihat isinya", "Mengarahkan mouse ke atasnya tanpa mengklik untuk melihat URL asli", "Menyalin dan menempelkannya di browser baru"], 'answer' => 1 ],
                    3 => ['type' => 'materi', 'title' => 'Smishing dan Vishing', 'duration' => '4 menit', 'content' => "<h3>Bukan Hanya Email</h3><p><strong>Smishing</strong> adalah phishing yang dilakukan melalui SMS. Contoh klasiknya adalah SMS 'Selamat Anda mendapatkan hadiah...'</p><p><strong>Vishing</strong> (Voice Phishing) adalah phishing melalui telepon, di mana penipu mencoba meyakinkan Anda untuk memberikan informasi melalui percakapan suara.</p>"],
                    4 => ['type' => 'materi', 'title' => 'Quishing: Jebakan di Balik QR Code', 'duration' => '4 menit', 'content' => "<h3>Jangan Asal Scan!</h3><p><strong>Quishing (QR Code Phishing)</strong> adalah teknik baru di mana pelaku menempel stiker QR code palsu di atas QR code yang asli (misalnya di tempat parkir). Saat Anda scan, Anda akan diarahkan ke situs web phishing untuk mencuri data.</p>"]
                ]
            ],
            3 => [
                'title' => 'Studi Kasus & Teknik Lanjutan',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Studi Kasus: Undangan .apk', 'duration' => '5 menit', 'video_embed_url' => 'https://www.youtube.com/embed/f9tW5A4A5gA', 'content' => "<h3>Modus Paling Berbahaya</h3><p>Penipuan yang marak adalah mengirim file berekstensi <strong>.apk</strong> melalui WhatsApp dengan menyamar sebagai undangan pernikahan atau resi paket. Meng-install file ini akan memasang malware yang bisa mencuri SMS, termasuk kode OTP m-banking.</p><p><strong>PENTING:</strong> Jangan pernah install aplikasi dari luar sumber resmi.</p>"],
                    2 => ['type' => 'kuis', 'title' => 'Kuis: Modus APK', 'duration' => '2 menit', 'question' => "File dengan ekstensi apa yang sangat berbahaya jika dikirim via WhatsApp dari sumber tak dikenal?", 'options' => [".jpg (gambar)", ".pdf (dokumen)", ".apk (aplikasi)"], 'answer' => 2 ],
                    3 => ['type' => 'materi', 'title' => 'Spear Phishing & BEC', 'duration' => '5 menit', 'video_embed_url' => 'https://www.youtube.com/embed/rSLi4h_Pylg', 'content' => "<h3>Serangan Tertarget & Kelas Kakap</h3><p><strong>Spear Phishing</strong> adalah serangan yang sangat tertarget dan personal. Pelaku sudah meriset targetnya.</p><p><strong>Business Email Compromise (BEC)</strong> adalah jenis spear phishing yang menargetkan perusahaan, biasanya dengan menyamar sebagai CEO untuk meminta transfer dana.</p>"],
                    4 => ['type' => 'materi', 'title' => 'Langkah Verifikasi & Pelaporan', 'duration' => '4 menit', 'content' => "<h3>Jangan Langsung Percaya, Verifikasi & Laporkan!</h3><p>Mendapat pesan mencurigakan? Lakukan verifikasi dengan menelepon pihak terkait melalui nomor resmi. Jika Anda yakin itu phishing, gunakan fitur 'Laporkan Phishing' di email Anda untuk membantu melindungi pengguna lain.</p>"],
                ]
            ]
        ]
    ],
    'password' => [
        'title' => 'Kekuatan Password',
        'subtitle' => 'Kunci Digital & Keamanannya',
        'icon' => 'fa-key',
        'chapters' => [
            1 => [
                'title' => 'Fondasi Password yang Kokoh',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Mengapa \'password123\' Berbahaya?', 'duration' => '4 menit', 'video_embed_url' => 'https://www.youtube.com/embed/r_o3-pGZ_iY', 'content' => "<h3>Anatomi Password Lemah</h3><p>Password seperti '123456' atau 'password' bisa dibobol dalam <strong>kurang dari satu detik</strong> oleh komputer modern. Peretas menggunakan program yang mencoba miliaran kombinasi per detik (Brute-force Attack).</p>"],
                    2 => ['type' => 'materi', 'title' => 'Prinsip Emas: Panjang > Rumit', 'duration' => '6 menit', 'video_embed_url' => 'https://www.youtube.com/embed/IduDkFdb_iI', 'content' => "<h3>Membuat Passphrase</h3><p>Prinsip modern adalah: <strong>panjang adalah kekuatan.</strong> Gunakan metode <strong>passphrase</strong>: gabungkan 4-5 kata acak yang tidak berhubungan, contoh: <code>kopi-pohon-baterai-jingga</code>. Ini sangat panjang, mudah diingat, namun super sulit ditebak.</p>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Kekuatan Password', 'duration' => '2 menit', 'question' => "Manakah password yang secara teori paling kuat?", 'options' => ["admin123!!", "Mei2025*", "meja-kuning-lari-pagi"], 'answer' => 2],
                    4 => ['type' => 'materi', 'title' => 'Hal-hal yang Harus Dihindari', 'duration' => '4 menit', 'content' => "<h3>Jangan Gunakan Informasi Pribadi!</h3><p>Hindari menggunakan informasi yang mudah ditebak dalam password Anda, seperti:</p><ul><li>Nama Anda, pasangan, anak, atau hewan peliharaan.</li><li>Tanggal lahir atau tanggal penting lainnya.</li><li>Pola keyboard yang mudah seperti <code>qwerty</code> atau <code>asdfgh</code>.</li><li>Mengganti huruf dengan simbol yang mirip (misal: 'a' menjadi '@') adalah taktik lama yang sudah mudah ditebak.</li></ul>"],
                ]
            ],
            2 => [
                'title' => 'Manajemen Password Modern',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Bahaya Daur Ulang Password', 'duration' => '5 menit', 'content' => "<h3>Satu Kunci untuk Semua Pintu?</h3><p>Ini adalah kesalahan paling umum. Jika Anda menggunakan password yang sama untuk banyak akun, dan salah satu akun bocor, peretas bisa menggunakan kombinasi email dan password itu untuk membobol semua akun Anda yang lain. Serangan ini disebut <strong>Credential Stuffing</strong>.</p><blockquote>Aturan Wajib: <strong>Satu Akun, Satu Password Unik.</strong></blockquote>"],
                    2 => ['type' => 'materi', 'title' => 'Solusi Cerdas: Password Manager', 'duration' => '7 menit', 'video_embed_url' => 'https://www.youtube.com/embed/Xp32iGKO3fA', 'content' => "<h3>Gudang Password Digital Anda</h3><p>Pada materi sebelumnya, kita sepakat bahwa menggunakan password yang sama di banyak situs adalah resep bencana. Tapi, bagaimana cara mengingat puluhan password unik yang berbeda-beda seperti <code>sK8!z@9p#R&2</code> atau <code>meja-kuning-lari-pagi</code>? Jawabannya: <strong>Jangan diingat. Biarkan mesin yang melakukannya.</strong></p><h4>Memperkenalkan Password Manager</h4><p>Password Manager adalah sebuah aplikasi yang bertindak sebagai <strong>brankas digital (encrypted vault)</strong> super aman untuk semua password Anda. Cara kerjanya sederhana namun jenius:</p><ol><li><strong>Satu Password untuk Mengunci Semua:</strong> Anda hanya perlu membuat dan mengingat <strong>satu</strong> Master Password yang sangat kuat. Ini adalah kunci utama untuk membuka brankas Anda.</li><li><strong>Menyimpan & Mengisi Otomatis:</strong> Saat Anda mendaftar di situs baru, Password Manager akan menawarkan untuk membuatkan password acak yang super kuat (misal: <code>Jk7*n!Pq$@3w#</code>) dan menyimpannya. Saat Anda ingin login lagi, ia akan mengisinya secara otomatis.</li><li><strong>Tersinkronisasi Antar Perangkat:</strong> Sebagian besar Password Manager modern bisa sinkron antara laptop, PC, dan HP Anda, sehingga semua password Anda selalu tersedia di mana pun.</li></ol><h4>Keuntungan Utama yang Mengubah Segalanya</h4><ul><li><strong>Keamanan Maksimal:</strong> Anda bisa menggunakan password yang berbeda dan sangat rumit untuk setiap akun tanpa perlu pusing.</li><li><strong>Kemudahan Luar Biasa:</strong> Tidak ada lagi drama 'Lupa Password'. Cukup satu klik untuk login.</li><li><strong>Benteng Anti-Phishing:</strong> Ini adalah keuntungan tersembunyi! Password Manager mengaitkan password dengan alamat situs yang benar (misal: <code>facebook.com</code>). Jika Anda masuk ke situs phishing (misal: <code>faceboook.com</code>), Password Manager tidak akan menawarkan fitur auto-fill. Ini menjadi pertanda jelas bahwa situs tersebut palsu!</li><li><strong>Penyimpanan Aman Selain Password:</strong> Anda juga bisa menyimpan data sensitif lain seperti catatan rahasia, data kartu kredit, atau lisensi software dengan aman di dalamnya.</li></ul><p>Mengadopsi Password Manager adalah langkah tunggal paling efektif yang bisa Anda lakukan untuk meningkatkan keamanan digital Anda secara drastis.</p>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Manajemen Password', 'duration' => '2 menit', 'question' => "Alat bantu yang paling direkomendasikan untuk mengelola banyak password unik adalah...", 'options' => ["Buku catatan fisik", "File Microsoft Excel", "Password Manager"], 'answer' => 2],
                    4 => ['type' => 'materi', 'title' => 'Panduan Memilih Password Manager', 'duration' => '8 menit', 'content' => "<h3>Memilih Gudang Digital Terbaik Anda</h3><p>Menggunakan Password Manager adalah langkah paling signifikan untuk meningkatkan keamanan akun Anda. Tapi dengan banyaknya pilihan, mana yang terbaik? Berikut adalah panduan untuk memilihnya.</p><h4>1. Memahami Cara Kerjanya</h4><p>Anggap Password Manager sebagai brankas bank digital super aman (disebut <strong>encrypted vault</strong>). Semua password Anda disimpan di dalamnya dalam bentuk terenkripsi. Anda hanya perlu mengingat satu kunci untuk membuka brankas ini, yaitu <strong>Master Password</strong>. Karena ini adalah satu-satunya kunci, pastikan Master Password Anda sangat kuat dan unik!</p><h4>2. Kriteria Penting Saat Memilih</h4><ul><li><strong>Keamanan (Arsitektur Zero-Knowledge):</strong> Ini yang terpenting. Pilih penyedia yang menggunakan arsitektur 'zero-knowledge'. Artinya, hanya Anda yang bisa membuka brankas Anda dengan Master Password. Pihak perusahaan (misal: Bitwarden atau 1Password) sekalipun tidak bisa melihat isi password Anda, bahkan jika mereka mau.</li><li><strong>Kemudahan Penggunaan (User Experience):</strong> Cari yang memiliki antarmuka yang bersih, serta ekstensi browser (untuk PC/Laptop) dan aplikasi mobile (untuk HP) yang andal. Fitur <em>auto-fill</em> yang baik akan sangat memudahkan hidup Anda.</li><li><strong>Fitur Tambahan:</strong> Fitur seperti generator password, penyimpanan catatan aman (secure notes), dan kemampuan berbagi password dengan aman kepada keluarga atau tim adalah nilai tambah yang besar.</li><li><strong>Reputasi dan Audit Keamanan:</strong> Gunakan penyedia yang sudah dikenal luas dan secara rutin menjalani audit keamanan oleh pihak ketiga. Ini menunjukkan transparansi dan komitmen mereka terhadap keamanan.</li></ul><h4>3. Rekomendasi Populer (2025)</h4><blockquote><strong>Bitwarden:</strong> Pilihan terbaik bagi kebanyakan orang. Bersifat <strong>open-source</strong> (kodenya bisa diaudit siapa saja) dan menawarkan paket gratis yang sangat lengkap dan fungsional. Sangat direkomendasikan jika Anda baru memulai.</blockquote><blockquote><strong>1Password:</strong> Dianggap memiliki antarmuka pengguna (UI/UX) terbaik dan fitur untuk keluarga yang sangat baik. Ini adalah pilihan premium (berbayar) yang sangat populer karena kemudahannya.</blockquote><blockquote><strong>KeePass:</strong> Untuk pengguna tingkat lanjut yang menginginkan kontrol penuh. Ini adalah aplikasi offline di mana Anda menyimpan file brankas Anda sendiri (misalnya di komputer atau di Google Drive pribadi). Lebih rumit, tapi memberi Anda kendali 100% atas data Anda.</blockquote><p>Lakukan riset kecil Anda sendiri, tapi memulai dengan salah satu dari tiga ini adalah pilihan yang sangat aman dan tepat.</p>"],
                ]
            ],
            3 => [
                'title' => 'Benteng Pertahanan Tambahan',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Pentingnya Autentikasi 2 Faktor (2FA)', 'duration' => '7 menit', 'video_embed_url' => 'https://www.youtube.com/embed/O5Y_A10fSzE', 'content' => "<h3>Benteng Pertahanan Terakhir Anda</h3><p>Bayangkan Anda sudah memiliki password terkuat di dunia. Sayangnya, password tersebut bocor karena kebocoran data di salah satu situs yang Anda gunakan. Apa yang terjadi? Peretas bisa langsung masuk ke akun Anda. Inilah mengapa kita butuh benteng pertahanan terakhir: <strong>Autentikasi Dua Faktor (2FA)</strong>.</p><h4>Konsep Kunci Ganda</h4><p>2FA adalah lapisan keamanan tambahan yang mewajibkan Anda membuktikan identitas melalui dua cara berbeda. Prinsipnya sederhana dan sudah kita gunakan sehari-hari, contohnya saat di ATM:</p><ul><li><strong>Faktor 1 (Sesuatu yang Anda Tahu):</strong> PIN ATM Anda.</li><li><strong>Faktor 2 (Sesuatu yang Anda Miliki):</strong> Kartu ATM fisik Anda.</li></ul><p>Tanpa salah satunya, transaksi tidak bisa dilakukan. Konsep yang sama berlaku di dunia digital. Dengan 2FA aktif, untuk login Anda butuh:</p><ol><li><strong>Password Anda</strong> (Sesuatu yang Anda Tahu).</li><li><strong>Kode unik dari HP Anda</strong> (Sesuatu yang Anda Miliki).</li></ol><h4>Bagaimana 2FA Menggagalkan Peretas?</h4><p>Mari kita lihat skenario Rian dari bab sebelumnya. Password emailnya bocor. Peretas mencoba login dari perangkat mereka.</p><blockquote>Tanpa 2FA, peretas akan <strong>langsung berhasil masuk</strong>. Game over.</blockquote><blockquote>Dengan 2FA, setelah peretas memasukkan password yang benar, sistem akan meminta 'kode verifikasi 6 digit yang baru saja dikirim ke HP Rian'. Peretas tidak memiliki HP Rian, sehingga mereka <strong>TERBENTUR TEMBOK</strong> dan gagal masuk. Di saat yang sama, Rian mendapatkan notifikasi login dan sadar akunnya dalam bahaya, memberinya waktu untuk segera mengganti password.</blockquote><p>2FA secara efektif membuat password Anda yang dicuri menjadi tidak berguna bagi peretas.</p><h4>Aktifkan Sekarang!</h4><p>Mengaktifkan 2FA adalah langkah tunggal paling berdampak yang bisa Anda lakukan untuk mengamankan kehidupan digital Anda. Jika Anda hanya bisa melakukan satu hal setelah membaca modul ini, lakukanlah ini: <strong>aktifkan 2FA di akun email utama Anda sekarang juga.</strong></p>"],
                    2 => ['type' => 'materi', 'title' => 'Membedah Jenis-jenis 2FA', 'duration' => '8 menit', 'content' => "<h3>Tidak Semua 2FA Sama Kuatnya</h3><p>Setelah Anda memutuskan untuk menggunakan 2FA, langkah selanjutnya adalah memilih metodenya. Setiap metode memiliki tingkat keamanan dan kemudahan yang berbeda. Mari kita bedah tiga yang paling umum.</p><h4>1. Kode via SMS atau Telepon (Level: Baik)</h4><p>Ini adalah metode yang paling banyak ditemui. Saat login, sistem akan mengirimkan kode 4-6 digit ke nomor HP Anda yang terdaftar.</p><ul><li><strong>Kelebihan:</strong> Sangat mudah digunakan, hampir semua orang punya nomor HP, tidak perlu install aplikasi tambahan.</li><li><strong>Kelemahan Utama:</strong> Rentan terhadap serangan <strong>SIM Swap Fraud</strong>. Ini adalah modus di mana penipu berhasil meyakinkan operator seluler untuk mentransfer nomor HP Anda ke kartu SIM baru milik mereka. Begitu berhasil, semua kode 2FA Anda akan masuk ke HP penipu.</li></ul><h4>2. Aplikasi Authenticator (Level: Lebih Baik & Direkomendasikan)</h4><p>Metode ini menggunakan aplikasi khusus di HP Anda (seperti Google Authenticator, Microsoft Authenticator, atau Authy) untuk menghasilkan kode yang terus berubah setiap 30 detik. Ini berdasarkan algoritma <strong>TOTP (Time-based One-Time Password)</strong>.</p><ul><li><strong>Kelebihan:</strong> Jauh lebih aman dari SIM Swap karena kode dihasilkan langsung di perangkat Anda (offline) dan tidak dikirim melalui jaringan seluler yang rentan.</li><li><strong>Kelemahan:</strong> Anda perlu menginstall aplikasi. Jika HP hilang dan Anda tidak punya kode cadangan (backup codes) atau sinkronisasi cloud (seperti di Authy), Anda bisa terkunci dari akun Anda.</li></ul><h4>3. Kunci Keamanan Fisik / U2F Key (Level: Terbaik)</h4><p>Ini adalah standar emas keamanan saat ini. Bentuknya seperti sebuah USB flash drive kecil (contoh merek: YubiKey, Google Titan Key).</p><ul><li><strong>Kelebihan:</strong> Keamanan tingkat tertinggi. Hampir mustahil untuk di-phishing. Saat login, Anda harus mencolokkan kunci ini ke port USB dan menyentuhnya secara fisik. Tidak ada kode yang bisa dicuri atau dicegat.</li><li><strong>Kelemahan:</strong> Anda harus membeli perangkatnya dan harus selalu membawanya. Jika hilang, Anda harus menggunakan metode backup lain yang sudah disiapkan.</li></ul><blockquote><strong>Rekomendasi:</strong> Untuk kebanyakan orang, menggunakan <strong>Aplikasi Authenticator</strong> adalah pilihan terbaik yang menyeimbangkan antara keamanan tingkat tinggi dan kemudahan penggunaan. Gunakan metode ini untuk semua akun penting Anda.</blockquote>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Jenis 2FA', 'duration' => '2 menit', 'question' => "Metode 2FA manakah yang dianggap paling aman?", 'options' => ["Kode via SMS", "Kode via Aplikasi Authenticator", "Kunci Fisik (Hardware Key)"], 'answer' => 2],
                    4 => ['type' => 'materi', 'title' => 'Langkah Darurat Saat Akun Dibobol', 'duration' => '5 menit', 'content' => "<h3>Jangan Panik, Bertindak Cepat!</h3><p>Jika Anda curiga akun Anda telah dibobol, lakukan langkah berikut:</p><ol><li>Segera ganti password akun tersebut.</li><li>Jika memungkinkan, aktifkan fitur 'Sign out from all other sessions' (Keluar dari semua sesi lain).</li><li>Periksa aktivitas akun untuk melihat apakah ada tindakan yang tidak Anda kenali.</li><li>Aktifkan 2FA jika belum.</li><li>Peringatkan kontak Anda jika ada kemungkinan akun Anda disalahgunakan untuk menipu mereka.</li></ol>"],
                ]
            ]
        ]
    ],
     // =================================================================
    // ===== MODUL 4: REKAYASA SOSIAL (SOCIAL ENGINEERING) - VERSI SUPER LENGKAP =====
    // =================================================================
   'rekayasa-sosial' => [
        'title' => 'Rekayasa Sosial',
        'subtitle' => 'Seni Memanipulasi Psikologi Manusia',
        'icon' => 'fa-theater-masks',
        'chapters' => [
            1 => [
                'title' => 'Pengantar: Peretasan Pikiran',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Apa Itu Rekayasa Sosial?', 'duration' => '5 menit', 'content' => "<h3>Bukan Sekadar Meretas Kode</h3><p>Rekayasa Sosial adalah seni memanipulasi, memengaruhi, atau menipu orang lain agar mereka memberikan informasi rahasia atau melakukan tindakan tertentu yang menguntungkan penyerang. Ini adalah serangan terhadap 'human-firewall', yaitu Anda.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Empat Vektor Serangan Utama', 'duration' => '6 menit', 'content' => "<h3>Pilar-Pilar Manipulasi</h3><p>Pelaku sering memanfaatkan empat pemicu emosi utama:</p><ul><li><strong>Otoritas:</strong> Menyamar sebagai atasan atau polisi untuk memberi perintah.</li><li><strong>Intimidasi:</strong> Mengancam dengan konsekuensi negatif, 'Akun Anda akan ditutup!'.</li><li><strong>Urgensi:</strong> Menciptakan tekanan waktu, 'Penawaran ini berakhir dalam 5 menit!'.</li><li><strong>Kepercayaan:</strong> Membangun hubungan palsu atau menyamar sebagai teman.</li></ul>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Vektor Serangan', 'duration' => '2 menit', 'question' => "Telepon dari 'polisi' yang menuduh Anda melakukan kejahatan adalah contoh penggunaan vektor...", 'options' => ["Otoritas", "Urgensi", "Kepercayaan"], 'answer' => 0 ],
                    4 => ['type' => 'materi', 'title' => 'Studi Kasus: Penipuan CEO (BEC)', 'duration' => '6 menit', 'content' => "<h3>Perintah Palsu dari 'Atasan'</h3><p>Seorang penipu melakukan riset dan mengetahui nama CEO dan Manajer Keuangan. Ia kemudian membuat email palsu yang sangat mirip dengan email CEO, meminta Manajer Keuangan untuk segera mentransfer dana ke rekening vendor 'rahasia'. Ini adalah contoh klasik Business Email Compromise (BEC).</p>"],
                ]
            ],
            2 => [
                'title' => 'Teknik Berbasis Komputer',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Phishing: Umpan Digital', 'duration' => '5 menit', 'content' => "<h3>Jebakan Paling Umum</h3><p>Phishing adalah bentuk rekayasa sosial yang paling umum, menggunakan email, SMS (Smishing), atau pesan instan sebagai media pengiriman 'umpan' untuk mencuri data.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Baiting: Umpan Rasa Penasaran', 'duration' => '5 menit', 'content' => "<h3>Jebakan Rasa Ingin Tahu</h3><p>Pernah melihat USB drive tergeletak di parkiran? Itulah contoh 'baiting' atau umpan. Pelaku sengaja meninggalkan perangkat yang sudah terisi malware, berharap ada orang yang penasaran dan mencolokkannya ke komputer.</p>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Teknik Manipulasi', 'duration' => '2 menit', 'question' => "Meninggalkan USB drive yang terinfeksi malware di tempat umum adalah contoh teknik...", 'options' => ["Pretexting", "Baiting", "Quid Pro Quo"], 'answer' => 1 ],
                    4 => ['type' => 'materi', 'title' => 'Scareware: Menakut-nakuti Korban', 'duration' => '4 menit', 'content' => "<h3>Pop-up Peringatan Palsu</h3><p>Scareware adalah malware yang menakut-nakuti Anda dengan pop-up palsu seperti 'Komputer Anda Terinfeksi 305 Virus! Klik di sini untuk membersihkan!'. Tujuannya adalah agar Anda membeli software antivirus palsu atau menginstall malware lain.</p>"],
                ]
            ],
            3 => [
                'title' => 'Teknik Berbasis Interaksi Manusia',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Pretexting: Menciptakan Skenario Palsu', 'duration' => '6 menit', 'content' => "<h3>Membangun Narasi yang Meyakinkan</h3><p>Pretexting adalah inti dari rekayasa sosial. Pelaku menciptakan sebuah skenario (pretext) yang dibuat-buat untuk meyakinkan target agar memberikan informasi. Contohnya, menyamar sebagai petugas bank yang sedang melakukan 'update data keamanan'.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Vishing: Penipuan via Suara', 'duration' => '5 menit', 'content' => "<h3>Modus 'Tech Support' Palsu</h3><p>Anda menerima telepon dari seseorang yang mengaku dari 'Dukungan Teknis Microsoft'. Mereka mengklaim komputer Anda terinfeksi virus berbahaya dan menawarkan bantuan untuk membersihkannya dengan memberikan mereka akses remote. Ini adalah modus Vishing yang sangat umum.</p>"],
                    3 => ['type' => 'materi', 'title' => 'Tailgating: Membuntuti Masuk', 'duration' => '6 menit', 'content' => "<h3>Menumpang Tanpa Izin</h3><p>Tailgating adalah serangan fisik. Pelaku akan membuntuti seseorang yang memiliki akses sah ke sebuah gedung atau ruangan terbatas. Misalnya, dengan berpura-pura sedang menelepon sambil membawa tumpukan boks, berharap orang di depannya akan menahan pintu untuknya.</p>"],
                    4 => ['type' => 'kuis', 'title' => 'Kuis: Interaksi Manusia', 'duration' => '2 menit', 'question' => "Penipuan yang terjadi melalui panggilan telepon disebut...", 'options' => ["Phishing", "Smishing", "Vishing"], 'answer' => 2 ],
                ]
            ],
            4 => [
                'title' => 'Studi Kasus Lanjutan',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Penipuan Romantis (Romance Scam)', 'duration' => '6 menit', 'content' => "<h3>Jebakan Hati Berujung Rugi</h3><p>Pelaku akan membangun hubungan emosional dengan target di situs kencan atau media sosial selama berminggu-minggu atau berbulan-bulan. Setelah kepercayaan terbangun, mereka akan mulai meminta uang dengan berbagai alasan darurat (sakit, kecelakaan, dll.).</p>"],
                    2 => ['type' => 'materi', 'title' => 'Quid Pro Quo: Sesuatu untuk Sesuatu', 'duration' => '5 menit', 'content' => "<h3>Bantuan Palsu Berujung Bencana</h3><p>Mirip dengan baiting, 'Quid Pro Quo' berarti 'sesuatu untuk sesuatu'. Pelaku menawarkan bantuan atau hadiah kecil sebagai ganti informasi. Contoh: 'Saya akan berikan software premium gratis jika Anda memberikan password login Anda'.</p>"],
                    3 => ['type' => 'materi', 'title' => 'Diversion Theft: Pengalihan Paket', 'duration' => '5 menit', 'content' => "<h3>Mengubah Alamat Tujuan</h3><p>Ini adalah teknik di mana penipu menipu sebuah perusahaan pengiriman untuk mengirimkan barang ke alamat lain. Mereka akan menelepon kurir dan memberikan informasi palsu, seolah-olah mereka adalah penerima asli yang ingin mengubah alamat pengiriman.</p>"],
                    4 => ['type' => 'kuis', 'title' => 'Kuis: Studi Kasus', 'duration' => '2 menit', 'question' => "Menawarkan software gratis sebagai imbalan password adalah contoh dari...", 'options' => ["Baiting", "Tailgating", "Quid Pro Quo"], 'answer' => 2 ],
                ]
            ],
            5 => [
                'title' => 'Membangun "Human Firewall"',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Prinsip Zero Trust: Verifikasi Selalu', 'duration' => '7 menit', 'content' => "<h3>Verifikasi, Jangan Asumsi</h3><p>Prinsip utama melawan rekayasa sosial adalah <strong>Zero Trust</strong> atau 'Nol Kepercayaan'. Jangan pernah berasumsi bahwa seseorang adalah benar seperti yang mereka katakan. Selalu verifikasi permintaan yang tidak biasa melalui saluran komunikasi yang berbeda. Dapat email dari bos minta transfer dana? Telepon dia untuk konfirmasi.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Menjadi Skeptis yang Sehat', 'duration' => '5 menit', 'content' => "<h3>Berpikir Sebelum Bertindak</h3><p>Biasakan untuk berhenti sejenak sebelum mengklik atau memberikan informasi. Tanyakan pada diri sendiri: 'Apakah permintaan ini wajar? Mengapa orang ini membutuhkan informasi ini? Apakah ada cara lain untuk memverifikasinya?'.</p>"],
                    3 => ['type' => 'materi', 'title' => 'Cara Menolak dengan Sopan tapi Tegas', 'duration' => '5 menit', 'content' => "<h3>Melindungi Informasi Adalah Hak Anda</h3><p>Anda berhak menolak permintaan yang terasa aneh. Gunakan kalimat seperti, 'Mohon maaf, sesuai prosedur keamanan, saya tidak bisa memberikan informasi itu lewat telepon. Saya akan menghubungi nomor resmi perusahaan untuk verifikasi.' Ini adalah cara yang profesional untuk melindungi diri sendiri dan perusahaan.</p>"],
                    4 => ['type' => 'kuis', 'title' => 'Kuis: Pertahanan Diri', 'duration' => '2 menit', 'question' => "Prinsip 'Jangan langsung percaya, selalu verifikasi' dikenal sebagai...", 'options' => ["Human Firewall", "Zero Trust", "Social Engineering"], 'answer' => 1 ],
                ]
            ]
        ]
    ],
    // =================================================================
    // ===== MODUL 5: KEAMANAN JARINGAN DASAR - VERSI LENGKAP =====
    // =================================================================
    'keamanan-jaringan' => [
        'title' => 'Keamanan Jaringan Dasar',
        'subtitle' => 'Mengamankan Koneksi Internet Anda',
        'icon' => 'fa-wifi',
        'chapters' => [
            1 => [
                'title' => 'Ancaman di Jaringan Publik',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Bahaya Wi-Fi Publik', 'duration' => '5 menit', 'content' => "<h3>Koneksi Gratis, Risiko Mahal</h3><p>Wi-Fi gratis di kafe, bandara, atau hotel memang nyaman, tapi juga berbahaya. Jaringan ini seringkali tidak terenkripsi, artinya data yang Anda kirim (termasuk password atau data pribadi) bisa 'diintip' oleh siapa saja yang berada di jaringan yang sama. Serangan ini disebut <strong>Man-in-the-Middle (MITM)</strong>.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Jebakan "Evil Twin"', 'duration' => '6 menit', 'content' => "<h3>Wi-Fi Kembar yang Jahat</h3><p>Penipu bisa membuat hotspot Wi-Fi palsu dengan nama yang sangat mirip dengan Wi-Fi asli (misal: 'KopiKenangan_FreeWiFi' vs 'KopiKenangan_WiFiGratis'). Ini disebut serangan <strong>Evil Twin</strong>.</p><p>Jika Anda salah terhubung ke jaringan palsu ini, semua lalu lintas internet Anda akan melewati perangkat peretas, memungkinkan mereka untuk mencuri semua data Anda.</p>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Evil Twin', 'duration' => '2 menit', 'question' => "Serangan di mana peretas membuat hotspot Wi-Fi palsu disebut...", 'options' => ["Evil Twin", "Man-in-the-Middle", "Trojan"], 'answer' => 0 ],
                    4 => ['type' => 'materi', 'title' => 'DNS Spoofing: Keracunan Alamat', 'duration' => '5 menit', 'content' => "<h3>Dibawa ke Alamat yang Salah</h3><p>Dalam serangan DNS Spoofing, peretas 'meracuni' sistem DNS untuk mengalihkan Anda ke situs web palsu saat Anda mengetik alamat yang sah. Misalnya, Anda mengetik alamat m-banking, tapi malah diarahkan ke situs phishing yang tampilannya identik.</p>"],
                ]
            ],
            2 => [
                'title' => 'Solusi & Praktik Terbaik',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Gunakan VPN (Virtual Private Network)', 'duration' => '6 menit', 'content' => "<h3>Terowongan Aman Anda</h3><p>VPN adalah solusi terbaik saat menggunakan jaringan publik. VPN akan mengenkripsi semua lalu lintas data Anda, menciptakan 'terowongan' pribadi yang aman di dalam jaringan publik. Bahkan jika ada yang mengintip, mereka hanya akan melihat data acak yang tidak bisa dibaca.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Mengamankan Wi-Fi Rumah', 'duration' => '5 menit', 'content' => "<h3>Jangan Lupakan Jaringan Pribadi</h3><p>Pastikan Wi-Fi di rumah Anda juga aman:</p><ul><li>Ganti password default dari router Anda.</li><li>Gunakan enkripsi WPA2 atau WPA3 (jangan WEP atau WPA).</li><li>Buat password Wi-Fi yang kuat dan unik.</li><li>Sembunyikan nama jaringan Anda (SSID) jika memungkinkan.</li></ul>"],
                    3 => ['type' => 'kuis', 'title' => 'Kuis: Solusi Terbaik', 'duration' => '2 menit', 'question' => "Teknologi yang menciptakan 'terowongan' aman di jaringan publik disebut...", 'options' => ["Antivirus", "Firewall", "VPN"], 'answer' => 2 ],
                ]
            ],
            3 => [
                'title' => 'Memahami Firewall',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Firewall: Satpam Digital Anda', 'duration' => '6 menit', 'content' => "<h3>Menyaring Lalu Lintas Berbahaya</h3><p>Firewall berfungsi sebagai penghalang antara jaringan internal Anda (komputer Anda) dengan jaringan eksternal (internet). Ia memonitor dan mengontrol lalu lintas data yang masuk dan keluar berdasarkan aturan keamanan yang telah ditentukan. Sistem operasi modern seperti Windows dan macOS sudah memiliki firewall bawaan yang kuat.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Firewall vs. Antivirus', 'duration' => '5 menit', 'content' => "<h3>Dua Lini Pertahanan yang Berbeda</h3><p>Anggap saja <strong>Firewall</strong> adalah tembok dan gerbang rumah Anda yang menyaring siapa yang boleh masuk. Sedangkan <strong>Antivirus</strong> adalah satpam yang berpatroli di dalam rumah untuk menangani penyusup yang berhasil lolos. Keduanya sangat penting dan tidak bisa menggantikan satu sama lain.</p>"],
                ]
            ],
            4 => [
                'title' => 'DNS & Serangan Terkait',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'DNS: Buku Telepon Internet', 'duration' => '5 menit', 'content' => "<h3>Menerjemahkan Nama Menjadi Angka</h3><p>DNS (Domain Name System) berfungsi seperti buku telepon internet. Saat Anda mengetik <code>google.com</code>, DNS-lah yang menerjemahkannya menjadi alamat IP (misal: <code>172.217.166.110</code>) yang dipahami oleh komputer. Menggunakan server DNS yang aman sangat penting.</p>"],
                    2 => ['type' => 'materi', 'title' => 'DNS Hijacking: Salah Alamat Berbahaya', 'duration' => '6 menit', 'content' => "<h3>Dibawa ke Alamat yang Salah</h3><p>Dalam serangan DNS Hijacking, peretas mengubah pengaturan DNS Anda untuk mengarahkan Anda ke situs web palsu. Misalnya, saat Anda mengetik alamat m-banking, Anda malah diarahkan ke situs phishing yang tampilannya identik. Menggunakan DNS terenkripsi (DNS over HTTPS) dapat membantu mencegah ini.</p>"],
                ]
            ],
            5 => [
                'title' => 'Keamanan Perangkat IoT',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'IoT: Pedang Bermata Dua', 'duration' => '6 menit', 'content' => "<h3>Ancaman dari Perangkat Pintar</h3><p>Perangkat Internet of Things (IoT) seperti smart TV, kamera CCTV, atau bahkan kulkas pintar, bisa menjadi titik lemah dalam jaringan Anda jika tidak diamankan dengan benar. Peretas bisa mengeksploitasinya untuk masuk ke jaringan rumah Anda.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Tips Mengamankan Perangkat IoT', 'duration' => '5 menit', 'content' => "<h3>Langkah Sederhana, Dampak Besar</h3><ul><li>Selalu ganti password default dari perangkat IoT Anda.</li><li>Pastikan firmware-nya selalu di-update.</li><li>Jika memungkinkan, letakkan perangkat IoT di jaringan terpisah (guest network) dari perangkat utama Anda seperti laptop atau HP.</li></ul>"],
                ]
            ],
        ]
    ],
    // =================================================================
    // ===== MODUL 6: PERLINDUNGAN DATA PRIBADI - VERSI LENGKAP =====
    // =================================================================
    'data-pribadi' => [
        'title' => 'Perlindungan Data Pribadi',
        'subtitle' => 'Menjaga Jejak Digital Anda',
        'icon' => 'fa-user-secret',
        'chapters' => [
            1 => [
                'title' => 'Jejak Digital Anda',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Apa itu Jejak Digital?', 'duration' => '5 menit', 'content' => "<h3>Semua yang Anda Lakukan Online</h3><p>Setiap kali Anda online, Anda meninggalkan 'jejak digital'. Ini bisa berupa jejak aktif (yang sengaja Anda bagikan, seperti postingan media sosial) dan jejak pasif (yang dikumpulkan tanpa Anda sadari, seperti riwayat pencarian atau lokasi).</p><p>Memahami dan mengelola jejak ini sangat penting untuk privasi Anda.</p>"],
                    2 => ['type' => 'kuis', 'title' => 'Kuis: Jejak Digital', 'duration' => '2 menit', 'question' => "Postingan di Instagram termasuk jenis jejak digital apa?", 'options' => ["Pasif", "Aktif", "Keduanya"], 'answer' => 1 ],
                    3 => ['type' => 'materi', 'title' => 'Risiko "Oversharing"', 'duration' => '6 menit', 'content' => "<h3>Berbagi Berlebihan, Risiko Berlebihan</h3><p>Terlalu banyak berbagi informasi pribadi di media sosial (oversharing)—seperti tanggal lahir lengkap, alamat rumah, atau jadwal liburan—dapat dimanfaatkan oleh penjahat untuk pencurian identitas atau bahkan perampokan di dunia nyata.</p>"],
                    4 => ['type' => 'materi', 'title' => 'Audit Privasi Akun Anda', 'duration' => '7 menit', 'content' => "<h3>Mengambil Kendali Kembali</h3><p>Lakukan audit privasi secara berkala di akun media sosial Anda:</p><ul><li>Atur profil Anda menjadi 'Private' atau 'Friends Only'.</li><li>Tinjau aplikasi pihak ketiga mana yang memiliki akses ke akun Anda dan cabut akses yang tidak perlu.</li><li>Hati-hati dengan kuis atau game online yang meminta akses ke profil Anda.</li></ul>"],
                ]        
            ],
           2 => [
                'title' => 'Jejak Digital & Privasi',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Apa itu Jejak Digital?', 'duration' => '5 menit', 'content' => "<h3>Semua yang Anda Lakukan Online</h3><p>Setiap kali Anda online, Anda meninggalkan 'jejak digital'. Ini bisa berupa jejak aktif (yang sengaja Anda bagikan, seperti postingan media sosial) dan jejak pasif (yang dikumpulkan tanpa Anda sadari, seperti riwayat pencarian atau lokasi).</p><p>Memahami dan mengelola jejak ini sangat penting untuk privasi Anda.</p>"],
                    2 => ['type' => 'kuis', 'title' => 'Kuis: Jejak Digital', 'duration' => '2 menit', 'question' => "Postingan di Instagram termasuk jenis jejak digital apa?", 'options' => ["Pasif", "Aktif", "Keduanya"], 'answer' => 1 ],
                    3 => ['type' => 'materi', 'title' => 'Risiko "Oversharing"', 'duration' => '6 menit', 'content' => "<h3>Berbagi Berlebihan, Risiko Berlebihan</h3><p>Terlalu banyak berbagi informasi pribadi di media sosial (oversharing)—seperti tanggal lahir lengkap, alamat rumah, atau jadwal liburan—dapat dimanfaatkan oleh penjahat untuk pencurian identitas atau bahkan perampokan di dunia nyata.</p>"],
                    4 => ['type' => 'materi', 'title' => 'Audit Privasi Akun Anda', 'duration' => '7 menit', 'content' => "<h3>Mengambil Kendali Kembali</h3><p>Lakukan audit privasi secara berkala di akun media sosial Anda:</p><ul><li>Atur profil Anda menjadi 'Private' atau 'Friends Only'.</li><li>Tinjau aplikasi pihak ketiga mana yang memiliki akses ke akun Anda dan cabut akses yang tidak perlu.</li><li>Hati-hati dengan kuis atau game online yang meminta akses ke profil Anda.</li></ul>"],
                ]
            ],
            3 => [
                'title' => 'Data Breach & Enkripsi',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Anatomi Kebocoran Data (Data Breach)', 'duration' => '6 menit', 'content' => "<h3>Saat Data Anda Terjual di Pasar Gelap</h3><p>Kebocoran data terjadi ketika informasi rahasia di sebuah perusahaan (misalnya, e-commerce) berhasil dicuri oleh peretas. Data ini, yang bisa berisi email, password, dan nomor telepon Anda, seringkali dijual di forum-forum gelap (dark web).</p>"],
                    2 => ['type' => 'materi', 'title' => 'Enkripsi: Tameng Digital Anda', 'duration' => '6 menit', 'content' => "<h3>Percakapan yang Hanya Kalian yang Tahu</h3><p>Enkripsi End-to-End (E2EE) memastikan bahwa hanya pengirim dan penerima yang bisa membaca isi pesan. Bahkan penyedia layanan (seperti WhatsApp) tidak bisa mengintipnya. Inilah mengapa aplikasi pesan dengan E2EE sangat penting untuk komunikasi yang aman.</p>"],
                    3 => ['type' => 'materi', 'title' => 'Pentingnya HTTPS', 'duration' => '4 menit', 'content' => "<h3>Gembok di Address Bar</h3><p>Selalu pastikan situs web yang Anda kunjungi menggunakan <strong>HTTPS</strong> (ditandai dengan ikon gembok). Ini berarti koneksi antara browser Anda dan situs tersebut terenkripsi, melindungi data yang Anda kirimkan (seperti saat mengisi form login) dari penyadapan.</p>"],
                    4 => ['type' => 'kuis', 'title' => 'Kuis: Enkripsi', 'duration' => '2 menit', 'question' => "Teknologi yang memastikan hanya pengirim dan penerima yang bisa membaca pesan disebut...", 'options' => ["HTTPS", "Enkripsi End-to-End", "VPN"], 'answer' => 1 ],
                ]
            ],
            4 => [
                'title' => 'Enkripsi: Tameng Digital Anda',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Memahami Enkripsi End-to-End', 'duration' => '6 menit', 'content' => "<h3>Percakapan yang Hanya Kalian yang Tahu</h3><p>Enkripsi End-to-End (E2EE) memastikan bahwa hanya pengirim dan penerima yang bisa membaca isi pesan. Bahkan penyedia layanan (seperti WhatsApp) tidak bisa mengintipnya. Inilah mengapa aplikasi pesan dengan E2EE sangat penting untuk komunikasi yang aman.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Pentingnya HTTPS', 'duration' => '4 menit', 'content' => "<h3>Gembok di Address Bar</h3><p>Selalu pastikan situs web yang Anda kunjungi menggunakan <strong>HTTPS</strong> (ditandai dengan ikon gembok). Ini berarti koneksi antara browser Anda dan situs tersebut terenkripsi, melindungi data yang Anda kirimkan (seperti saat mengisi form login) dari penyadapan.</p>"],
                ]
            ],
            5 => [
                'title' => 'Hak Digital & Regulasi',
                'lessons' => [
                    1 => ['type' => 'materi', 'title' => 'Mengenal UU PDP Indonesia', 'duration' => '6 menit', 'content' => "<h3>Hak Anda sebagai Subjek Data</h3><p>Indonesia telah memiliki Undang-Undang Perlindungan Data Pribadi (UU PDP). Ini memberikan Anda hak untuk mengetahui data apa yang dikumpulkan tentang Anda, bagaimana data itu digunakan, dan hak untuk meminta penghapusan data tersebut. Memahami hak-hak ini memberdayakan Anda sebagai konsumen digital.</p>"],
                    2 => ['type' => 'materi', 'title' => 'Masa Depan Privasi', 'duration' => '5 menit', 'content' => "<h3>Peran Aktif Pengguna</h3><p>Masa depan privasi tidak hanya bergantung pada teknologi atau regulasi, tetapi juga pada kesadaran dan tindakan kita sebagai pengguna. Dengan menjadi lebih sadar akan data yang kita bagikan dan menuntut transparansi dari perusahaan, kita secara kolektif dapat menciptakan ekosistem digital yang lebih aman.</p>"],
                ]
            ],
        ]
    ],
];